version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker file
          command: |
            docker build . -t app
      - run:
          name: Run docker
          command: |
            docker run -d --name instance app
            docker run --network container:instance appropriate/curl --retry 10 --retry-connrefused http://localhost:8080
#  tests:
#    docker:
#      - image: curlimages/curl:latest
#    steps:
#      - run:
#          name: Do a curl
#          command: |
#            curl http://localhost:8080

workflows:
  my-workflow:
    jobs:
    - build
#    - tests:
#        requires:
#          - build