version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Build docker file
          command: |
            docker build . -t app