version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker file
          command: |
            docker build . -t app
  tests:
    docker:
      - image: curlimages/curl:latest
    steps:
      - run:
          name: Install curl
          command: |
            apt install curl
      - run:
          name: Do a curl
          command: |
            curl http://localhost:8080